site_name: Робот и точка

nav:
  - Общие сведения:  
     - general_info/characteristics.md
  - Назначение и цели проекта:
     - general_info/purpose.md
  - Глоссарий:
     - general_info/glossary.md
  - Описание бизнес-процессов:
    - description_of_business_processes/business_processes.md
  - Требования к системе: 
    - requirements/nfr.md
    - use_case_diagram.md 11-14-45-452.md
    - requirements/uc01.md
    - requirements/uc02.md
    - requirements/uc03.md
    - requirements/uc04.md
    - requirements/uc05.md
    - requirements/uc06.md
    - requirements/uc07.md
    - requirements/uc08.md
    - requirements/uc09.md
    - requirements/uc10.md
    - requirements/uc11.md
    - requirements/uc12.md
    - requirements/uc13.md
    - requirements/uc14.md
    - requirements/uc15.md
    - requirements/uc16.md

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition

plugins:
  - swagger-ui-tag
  - mermaid2
  - glightbox
  - search
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      allow_multiple_roots: false # in case your codebase contains more locations for diagrams (all ending in diagram_root)
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
